#!/usr/bin/env bash
set -euo pipefail

FEATURE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$FEATURE_DIR/../.." && pwd)"
STAMP="$(date +%Y%m%d_%H%M%S)"

export FLIP_TABLE_POLICY_NAME=CvRuleBasedPolicy
export FLIP_TABLE_TEST_NUM="${FLIP_TABLE_TEST_NUM:-1}"
export FLIP_TABLE_EVAL_MODE="${FLIP_TABLE_EVAL_MODE:-randomized}"
export FLIP_TABLE_TIME_OUT_LIMIT="${FLIP_TABLE_TIME_OUT_LIMIT:-4200}"
export FLIP_TABLE_CV_WARMUP_STEPS="${FLIP_TABLE_CV_WARMUP_STEPS:-100}"
export FLIP_TABLE_CV_SETTLED_SELECTION_STEPS="${FLIP_TABLE_CV_SETTLED_SELECTION_STEPS:-30}"
export FLIP_TABLE_CV_WRIST_SERVO_GAIN="${FLIP_TABLE_CV_WRIST_SERVO_GAIN:-0.80}"
export FLIP_TABLE_CV_WRIST_SERVO_MAX_CORRECTION_M="${FLIP_TABLE_CV_WRIST_SERVO_MAX_CORRECTION_M:-0.12}"
export FLIP_TABLE_CV_FIRST_ROLL_WRIST_SERVO_GAIN="${FLIP_TABLE_CV_FIRST_ROLL_WRIST_SERVO_GAIN:-0.35}"
export FLIP_TABLE_CV_FIRST_ROLL_WRIST_SERVO_MAX_CORRECTION_M="${FLIP_TABLE_CV_FIRST_ROLL_WRIST_SERVO_MAX_CORRECTION_M:-0.05}"
export FLIP_TABLE_CV_FIRST_ROLL_RECOVERY_SERVO_GAIN="${FLIP_TABLE_CV_FIRST_ROLL_RECOVERY_SERVO_GAIN:-0.80}"
export FLIP_TABLE_CV_FIRST_ROLL_RECOVERY_SERVO_MAX_CORRECTION_M="${FLIP_TABLE_CV_FIRST_ROLL_RECOVERY_SERVO_MAX_CORRECTION_M:-0.08}"
export FLIP_TABLE_CV_FIRST_ROLL_MAX_TRACKING_ERROR_M="${FLIP_TABLE_CV_FIRST_ROLL_MAX_TRACKING_ERROR_M:-0.09}"
export FLIP_TABLE_CV_FIRST_ROLL_MAX_STALL_STEPS="${FLIP_TABLE_CV_FIRST_ROLL_MAX_STALL_STEPS:-500}"
export FLIP_TABLE_CV_WRIST_VISUAL_SERVO_M_PER_PX="${FLIP_TABLE_CV_WRIST_VISUAL_SERVO_M_PER_PX:-0.0002}"
export FLIP_TABLE_CV_WRIST_VISUAL_SERVO_MAX_M="${FLIP_TABLE_CV_WRIST_VISUAL_SERVO_MAX_M:-0.08}"
export FLIP_TABLE_CV_WRIST_SHAFT_MIN_CONFIDENCE="${FLIP_TABLE_CV_WRIST_SHAFT_MIN_CONFIDENCE:-0.75}"
export FLIP_TABLE_CV_WRIST_SHAFT_MAX_CENTER_ERROR_PX="${FLIP_TABLE_CV_WRIST_SHAFT_MAX_CENTER_ERROR_PX:-8}"
export FLIP_TABLE_CV_WRIST_SERVO_INTEGRAL_GAIN="${FLIP_TABLE_CV_WRIST_SERVO_INTEGRAL_GAIN:-0.0}"
export FLIP_TABLE_CV_DEX1_GRASP_BLOCK_THRESHOLD_RAD="${FLIP_TABLE_CV_DEX1_GRASP_BLOCK_THRESHOLD_RAD:--0.017}"
export FLIP_TABLE_CV_GRASP_LOSS_LIMIT_STEPS="${FLIP_TABLE_CV_GRASP_LOSS_LIMIT_STEPS:-8}"
export FLIP_TABLE_CV_GRASP_GATE_STABLE_STEPS="${FLIP_TABLE_CV_GRASP_GATE_STABLE_STEPS:-4}"
export FLIP_TABLE_CV_GRASP_RETRY_ATTEMPTS="${FLIP_TABLE_CV_GRASP_RETRY_ATTEMPTS:-16}"
export FLIP_TABLE_CV_FIRST_ROLL_ADVANCE_INTERVAL="${FLIP_TABLE_CV_FIRST_ROLL_ADVANCE_INTERVAL:-5}"
export FLIP_TABLE_CV_MAX_CARTESIAN_LINEAR_SPEED_M_S="${FLIP_TABLE_CV_MAX_CARTESIAN_LINEAR_SPEED_M_S:-0.25}"
export FLIP_TABLE_CV_MAX_CARTESIAN_ANGULAR_SPEED_RAD_S="${FLIP_TABLE_CV_MAX_CARTESIAN_ANGULAR_SPEED_RAD_S:-0.75}"
export FLIP_TABLE_CV_MAX_DEX1_COMMAND_SPEED_S="${FLIP_TABLE_CV_MAX_DEX1_COMMAND_SPEED_S:-3.5}"
export FLIP_TABLE_WBC_JOINT_CONTINUITY_FILTER="${FLIP_TABLE_WBC_JOINT_CONTINUITY_FILTER:-true}"
export FLIP_TABLE_WBC_MAX_JOINT_SPEED_RAD_S="${FLIP_TABLE_WBC_MAX_JOINT_SPEED_RAD_S:-2.0}"
export FLIP_TABLE_WBC_MAX_JOINT_ACCELERATION_RAD_S2="${FLIP_TABLE_WBC_MAX_JOINT_ACCELERATION_RAD_S2:-8.0}"
export FLIP_TABLE_TABLE_YAW_RANGE_RAD="${FLIP_TABLE_TABLE_YAW_RANGE_RAD:-3.141592653589793}"
export FLIP_TABLE_SIM_OUTPUT_DIR="${FLIP_TABLE_SIM_OUTPUT_DIR:-$ROOT_DIR/outputs/flip_table_cv_rule_based/${STAMP}_cv_rule_based}"

REPORTER="$FEATURE_DIR/tools/write_cv_trial_report.py"
python3 "$REPORTER" "$FLIP_TABLE_SIM_OUTPUT_DIR"
status=0
if [[ -d "${ROBOFINALS_ROOT:-/workspace/robofinals}" ]]; then
  "$FEATURE_DIR/run_eval_in_container.sh" || status=$?
else
  "$FEATURE_DIR/run_eval.sh" || status=$?
fi
python3 "$REPORTER" "$FLIP_TABLE_SIM_OUTPUT_DIR" --exit-status "$status"
exit "$status"
