#!/usr/bin/env python3
"""Build event-based progress labels without modifying the source dataset."""

from __future__ import annotations

import argparse
from collections import Counter
import hashlib
import json
import sys
from pathlib import Path
from typing import Any

import pyarrow.parquet as pq
from huggingface_hub import snapshot_download

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from gr00t.progress_annotations import MILESTONE_NAMES, annotate_episode  # noqa: E402

DEFAULT_REPO_ID = "Team-RAMEN/IROS2026_RAMEN_suzuki_flip_table_2"
DEFAULT_REVISION = "0dc47877dfb2efbea796a059c81290c649bc773c"
PROGRESS_MANIFEST_NAME = "progress_manifest.json"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo-id", default=DEFAULT_REPO_ID)
    parser.add_argument("--revision", default=DEFAULT_REVISION)
    parser.add_argument("--source-root", type=Path)
    parser.add_argument(
        "--visual-rotation-sidecar",
        type=Path,
        help="Per-frame RGB table rotation generated by extract_flip_table_visual_rotation.py.",
    )
    parser.add_argument(
        "--output-root",
        type=Path,
        default=ROOT / "outputs" / "progress_sidecars" / "flip_table_v2",
    )
    parser.add_argument("--force", action="store_true")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    source_root = args.source_root or Path(
        snapshot_download(
            args.repo_id,
            repo_type="dataset",
            revision=args.revision,
            allow_patterns=["data/**/*.parquet", "meta/**/*.parquet", "meta/*.json"],
        )
    )
    output_root = args.output_root.resolve()
    sidecar_path = output_root / "progress.jsonl"
    manifest_path = output_root / PROGRESS_MANIFEST_NAME
    if not args.force and (sidecar_path.exists() or manifest_path.exists()):
        raise FileExistsError(f"{output_root} already contains progress output; pass --force")
    output_root.mkdir(parents=True, exist_ok=True)

    visual_annotations = (
        _load_visual_rotation_sidecar(args.visual_rotation_sidecar)
        if args.visual_rotation_sidecar is not None
        else {}
    )
    annotations = []
    for parquet_path in sorted(source_root.glob("data/**/*.parquet")):
        table = pq.read_table(
            parquet_path,
            columns=[
                "episode_index",
                "action.hand_cmd",
                "observation.state.hand_state",
                "action.ee_action",
                "action.robot_q_desired",
            ],
        )
        episode_values = table["episode_index"].to_pylist()
        for episode_index in sorted(set(int(value) for value in episode_values)):
            indices = [index for index, value in enumerate(episode_values) if int(value) == episode_index]
            episode = table.take(indices)
            visual = visual_annotations.get(episode_index)
            annotation = annotate_episode(
                episode_index=episode_index,
                hand_cmd=episode["action.hand_cmd"].to_pylist(),
                hand_state=episode["observation.state.hand_state"].to_pylist(),
                ee_action=episode["action.ee_action"].to_pylist(),
                robot_q_desired=episode["action.robot_q_desired"].to_pylist(),
                visual_rotation=None if visual is None else visual["rotation_rad"],
                visual_confidence=None if visual is None else visual["confidence"],
            )
            annotations.append(annotation.as_dict())

    annotations.sort(key=lambda item: item["episode_index"])
    _validate_complete_episode_set(annotations)
    sidecar_path.write_text(
        "".join(json.dumps(item, separators=(",", ":")) + "\n" for item in annotations)
    )
    summary = _summary(annotations, source_root)
    manifest = {
        "schema_version": "flip_table_progress_sidecar_manifest_v1",
        "dataset_repo_id": args.repo_id,
        "dataset_revision": args.revision,
        "source_root": source_root.resolve().as_posix(),
        "source_numeric_sha256": _numeric_fingerprint(source_root),
        "annotation_file": sidecar_path.name,
        "annotation_sha256": _sha256(sidecar_path),
        "visual_rotation_sidecar": (
            {
                "path": args.visual_rotation_sidecar.resolve().as_posix(),
                "sha256": _sha256(args.visual_rotation_sidecar),
            }
            if args.visual_rotation_sidecar is not None
            else None
        ),
        "milestones": list(MILESTONE_NAMES),
        "policy_input_exclusions": [
            "milestone labels",
            "progress labels",
            "future images",
            "sim ground truth",
            "object pose",
            "contact ground truth",
        ],
        "summary": summary,
    }
    manifest_path.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n")
    print(json.dumps(manifest, indent=2, sort_keys=True))


def _validate_complete_episode_set(annotations: list[dict[str, Any]]) -> None:
    indices = [int(item["episode_index"]) for item in annotations]
    if indices != list(range(174)):
        raise ValueError(f"expected exactly episodes 0..173, got {indices[:3]}...{indices[-3:]}")
    for item in annotations:
        if item["length"] != len(item["progress"]) or item["length"] != len(item["progress_mask"]):
            raise ValueError(f"progress length mismatch in episode {item['episode_index']}")


def _load_visual_rotation_sidecar(path: Path) -> dict[int, dict[str, Any]]:
    if not path.is_file():
        raise FileNotFoundError(path)
    values: dict[int, dict[str, Any]] = {}
    for line_number, line in enumerate(path.read_text().splitlines(), start=1):
        if not line.strip():
            continue
        item = json.loads(line)
        if item.get("schema_version") != "flip_table_visual_rotation_v1":
            raise ValueError(f"unsupported visual rotation schema at {path}:{line_number}")
        episode_index = int(item["episode_index"])
        if episode_index in values:
            raise ValueError(f"duplicate visual rotation episode {episode_index}")
        length = int(item["length"])
        if len(item["rotation_rad"]) != length or len(item["confidence"]) != length:
            raise ValueError(f"visual rotation length mismatch for episode {episode_index}")
        values[episode_index] = item
    if sorted(values) != list(range(174)):
        raise ValueError("visual rotation sidecar must contain exactly episodes 0..173")
    return values


def _summary(
    annotations: list[dict[str, Any]],
    source_root: Path,
) -> dict[str, Any]:
    return {
        "episode_count": len(annotations),
        "review_required_count": sum(bool(item["review_required"]) for item in annotations),
        "valid_by_milestone": {
            name: sum(bool(item["milestones"][name]["valid"]) for item in annotations)
            for name in MILESTONE_NAMES
        },
        "orientation_groups": _orientation_group_counts(source_root),
        "orientation_group_source": "meta/episodes.curation_orientation_cluster",
        "fixed_phase_segmentation": False,
    }


def _orientation_group_counts(source_root: Path) -> dict[str, int]:
    rows: list[dict[str, Any]] = []
    for path in sorted((source_root / "meta" / "episodes").glob("chunk-*/*.parquet")):
        rows.extend(
            pq.read_table(
                path,
                columns=["episode_index", "curation_orientation_cluster"],
            ).to_pylist()
        )
    rows.sort(key=lambda row: int(row["episode_index"]))
    indices = [int(row["episode_index"]) for row in rows]
    if indices != list(range(174)):
        raise ValueError(
            "orientation metadata must contain exactly episodes 0..173"
        )
    counts = Counter(str(int(row["curation_orientation_cluster"])) for row in rows)
    return dict(sorted(counts.items(), key=lambda item: int(item[0])))


def _numeric_fingerprint(root: Path) -> str:
    digest = hashlib.sha256()
    for path in sorted(root.glob("data/**/*.parquet")):
        digest.update(path.relative_to(root).as_posix().encode())
        digest.update(bytes.fromhex(_sha256(path)))
    return digest.hexdigest()


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


if __name__ == "__main__":
    main()
