"""Build ACT, Diffusion, or GR00T views over the shared LeRobot v3 data."""

from __future__ import annotations

import argparse
import copy
import hashlib
import importlib.util
import json
import math
import os
import random
import shutil
import sys
from pathlib import Path
from typing import Any

import numpy as np
from huggingface_hub import snapshot_download


FEATURE_ROOT = Path(__file__).resolve().parents[1]
REPO_ROOT = Path(__file__).resolve().parents[3]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from model.subtask_policy_training.lineage_sampling import (  # noqa: E402
    build_sampling_plan,
    canonical_condition,
    load_augmentation_records,
)
from model.subtask_policy_training import delta_action  # noqa: E402
from model.subtask_policy_training.gr00t.progress_annotations import (  # noqa: E402
    progress_horizons,
)


DEFAULT_CONFIG = FEATURE_ROOT / "configs" / "subtask_training.json"
MARKER_PATH = Path("meta/team_ramen_training_view.json")
SPLIT_PATH = Path("meta/team_ramen_episode_split.json")
SAMPLING_PLAN_PATH = Path("meta/team_ramen_lineage_sampling_plan.json")
SOURCE_AUGMENTATION_PATH = Path("meta/augmentation/episodes.jsonl")
MAPPING_PATH = FEATURE_ROOT / "gr00t" / "g1_full_body_mapping.py"
PRESERVED_DATA_KEYS = ("timestamp", "frame_index", "episode_index", "index", "task_index")
PRESERVED_EPISODE_KEYS = (
    "episode_index",
    "tasks",
    "length",
    "data/chunk_index",
    "data/file_index",
    "dataset_from_index",
    "dataset_to_index",
    "source_episode_index",
    "source_episode_name",
    "source_task",
    "source_start_sec",
    "source_end_sec",
    "source_frame_start_sec",
    "source_frame_end_sec",
)
VIDEO_EPISODE_SUFFIXES = ("chunk_index", "file_index", "from_timestamp", "to_timestamp")
STATS_NAMES = ("min", "max", "mean", "std", "count", "q01", "q10", "q50", "q90", "q99")
PROGRESS_HORIZON = 40
PROGRESS_KEY = "observation.progress_horizon"
PROGRESS_MASK_KEY = "observation.progress_mask"


def load_mapping_module() -> Any:
    spec = importlib.util.spec_from_file_location("g1_full_body_mapping", MAPPING_PATH)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"failed to load mapping module: {MAPPING_PATH}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


_mapping = load_mapping_module()


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo-id", required=True)
    parser.add_argument("--output-root", type=Path, required=True)
    parser.add_argument("--config", type=Path, default=DEFAULT_CONFIG)
    parser.add_argument("--policy-type", default="act")
    parser.add_argument("--source-root", type=Path)
    parser.add_argument("--revision")
    parser.add_argument("--training-condition")
    parser.add_argument(
        "--progress-sidecar",
        type=Path,
        help="Event-progress JSONL generated by build_flip_table_progress_sidecar.py.",
    )
    parser.add_argument(
        "--action-representation",
        choices=("absolute_target", delta_action.ACTION_REPRESENTATION),
    )
    parser.add_argument("--validation-fraction", type=float)
    parser.add_argument(
        "--test-episodes",
        help="Comma-separated fixed held-out episode indices. Their source lineages must be exclusive.",
    )
    parser.add_argument(
        "--train-episodes",
        help="Comma-separated fixed training episode indices. Non-selected episodes stay unused.",
    )
    parser.add_argument("--force", action="store_true")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    config = load_config(args.config)
    source_root = args.source_root or download_source_dataset(
        args.repo_id,
        config,
        revision=args.revision,
    )
    materialize_training_view(
        source_root=source_root,
        output_root=args.output_root,
        repo_id=args.repo_id,
        config=config,
        policy_type=args.policy_type,
        training_condition=args.training_condition,
        source_revision=args.revision,
        action_representation=args.action_representation,
        validation_fraction=args.validation_fraction,
        heldout_episode_indices=parse_episode_indices(args.test_episodes),
        training_episode_indices=parse_episode_indices(args.train_episodes),
        progress_sidecar=args.progress_sidecar,
        force=args.force,
    )
    print(f"Wrote {args.policy_type} training view to {args.output_root}")


def load_config(path: Path) -> dict[str, Any]:
    config = json.loads(path.read_text(encoding="utf-8"))
    if config.get("schema_version") != "subtask_training_v1":
        raise ValueError(f"unsupported training config schema: {config.get('schema_version')}")
    return config


def parse_episode_indices(value: str | None) -> list[int] | None:
    if value is None:
        return None
    values = [part.strip() for part in value.split(",") if part.strip()]
    if not values:
        raise ValueError("--test-episodes must contain at least one episode index")
    try:
        indices = [int(part) for part in values]
    except ValueError as exc:
        raise ValueError("--test-episodes must be comma-separated integers") from exc
    if any(index < 0 for index in indices) or len(indices) != len(set(indices)):
        raise ValueError("--test-episodes must be unique non-negative integers")
    return sorted(indices)


def resolve_action_representation(
    config: dict[str, Any], policy_type: str, requested: str | None = None
) -> str:
    representation = requested or str(
        config.get("training", {}).get("action_representation", "absolute_target")
    )
    if representation not in {"absolute_target", delta_action.ACTION_REPRESENTATION}:
        raise ValueError(f"unsupported action representation: {representation!r}")
    if representation == delta_action.ACTION_REPRESENTATION:
        if policy_type == "groot" or view_layout_for_policy(config, policy_type) != "robot_q_state19_action16":
            raise ValueError(
                "arm_delta_gripper_absolute is only valid for the upper-body ACT/DP/flow view"
            )
    return representation


def download_source_dataset(repo_id: str, config: dict[str, Any], *, revision: str | None = None) -> Path:
    allow_patterns = ["README.md", "meta/**", "data/**"]
    for source_key in training_video_map(config).values():
        allow_patterns.append(f"videos/{source_key}/**")
    return Path(
        snapshot_download(
            repo_id=repo_id,
            repo_type="dataset",
            revision=revision,
            allow_patterns=allow_patterns,
        )
    )


def materialize_training_view(
    *,
    source_root: Path,
    output_root: Path,
    repo_id: str,
    config: dict[str, Any],
    policy_type: str,
    training_condition: str | None = None,
    source_revision: str | None = None,
    action_representation: str | None = None,
    validation_fraction: float | None = None,
    heldout_episode_indices: list[int] | None = None,
    training_episode_indices: list[int] | None = None,
    progress_sidecar: Path | None = None,
    force: bool = False,
) -> None:
    if policy_type not in {"act", "diffusion", "flow_matching", "groot"}:
        raise ValueError(f"unsupported policy type: {policy_type!r}")
    action_representation = resolve_action_representation(
        config, policy_type, action_representation
    )
    pa, pq = require_pyarrow()
    source_root = source_root.resolve()
    output_root = output_root.resolve()
    if (
        source_root == output_root
        or output_root.is_relative_to(source_root)
        or source_root.is_relative_to(output_root)
    ):
        raise ValueError("source-root and output-root must be separate, non-nested directories")
    validate_source_contract(source_root, config)
    if training_condition is not None:
        training_condition = canonical_condition(training_condition)
    source_fingerprint = source_dataset_fingerprint(source_root)
    progress_annotations = (
        load_progress_sidecar(progress_sidecar) if progress_sidecar is not None else None
    )
    expected_marker = build_marker(
        repo_id=repo_id,
        source_root=source_root,
        config=config,
        policy_type=policy_type,
        training_condition=training_condition,
        source_revision=source_revision,
        action_representation=action_representation,
        validation_fraction=validation_fraction,
        heldout_episode_indices=heldout_episode_indices,
        training_episode_indices=training_episode_indices,
        source_fingerprint=source_fingerprint,
        progress_sidecar=progress_sidecar,
    )
    if output_root.exists():
        marker_path = output_root / MARKER_PATH
        if not force and marker_path.exists() and read_json(marker_path) == expected_marker:
            print(f"Reusing existing training view at {output_root}")
            return
        if not force:
            raise FileExistsError(f"{output_root} exists; pass --force to replace it")

    temporary_root = output_root.with_name(f".{output_root.name}.tmp-{os.getpid()}")
    if temporary_root.exists():
        shutil.rmtree(temporary_root)

    try:
        info = read_json(source_root / "meta" / "info.json")
        source_features = copy.deepcopy(info["features"])
        source_stats = read_json(source_root / "meta" / "stats.json")
        video_map = training_video_map(config)
        view_layout = view_layout_for_policy(config, policy_type)
        episode_split = build_grouped_episode_split(
            source_root,
            config=config,
            pq=pq,
            validation_fraction=validation_fraction,
            heldout_episode_indices=heldout_episode_indices,
            training_episode_indices=training_episode_indices,
        )
        training_episode_indices = set(episode_split["splits"]["train"]["episode_indices"])
        sampling_plan = None
        if training_condition is not None:
            augmentation_path = source_root / SOURCE_AUGMENTATION_PATH
            if not augmentation_path.is_file():
                raise FileNotFoundError(
                    "lineage-balanced training requires augmentation metadata: "
                    f"{augmentation_path}"
                )
            sampling_plan = build_sampling_plan(
                records=load_augmentation_records(augmentation_path),
                train_episode_indices=sorted(training_episode_indices),
                condition=training_condition,
                split_sha256=str(episode_split["sha256"]),
            )
            training_episode_indices = {
                int(record["episode_index"]) for record in sampling_plan["episodes"]
            }
        temporary_root.mkdir(parents=True)
        (temporary_root / "data").mkdir()
        (temporary_root / "meta").mkdir()
        (temporary_root / "videos").mkdir()
        if progress_sidecar is not None:
            progress_output = temporary_root / "meta" / "progress" / "progress.jsonl"
            progress_output.parent.mkdir(parents=True)
            shutil.copy2(progress_sidecar, progress_output)

        copy_optional_file(source_root / "README.md", temporary_root / "README.md")
        copy_required_file(
            source_root / "meta" / "tasks.parquet",
            temporary_root / "meta" / "tasks.parquet",
        )
        source_augmentation = source_root / "meta" / "augmentation"
        if source_augmentation.is_dir():
            shutil.copytree(source_augmentation, temporary_root / "meta" / "augmentation")
        mapped_vector_stats = rewrite_data_parquets(
            source_root,
            temporary_root,
            config=config,
            policy_type=policy_type,
            action_representation=action_representation,
            stats_episode_indices=training_episode_indices,
            progress_annotations=progress_annotations,
            pa=pa,
            pq=pq,
        )
        rewrite_episode_metadata(
            source_root,
            temporary_root,
            config=config,
            policy_type=policy_type,
            action_representation=action_representation,
            pa=pa,
            pq=pq,
        )
        link_video_dirs(source_root, temporary_root, video_map)

        info["features"] = build_training_features(
            config=config,
            policy_type=policy_type,
            action_representation=action_representation,
            source_features=source_features,
            include_progress=progress_annotations is not None,
        )
        write_json(temporary_root / "meta" / "info.json", info)
        if view_layout == "real_g1_relative_eef_relative_joints":
            write_json(
                temporary_root / "meta" / "modality.json",
                _mapping.build_real_g1_relative_eef_modality_json(list(video_map)),
            )
        write_json(
            temporary_root / "meta" / "stats.json",
            build_training_stats(
                config=config,
                policy_type=policy_type,
                action_representation=action_representation,
                source_stats=source_stats,
                source_features=source_features,
                mapped_vector_stats=mapped_vector_stats,
            ),
        )
        write_json(temporary_root / SPLIT_PATH, episode_split)
        if sampling_plan is not None:
            write_json(temporary_root / SAMPLING_PLAN_PATH, sampling_plan)
        write_json(temporary_root / MARKER_PATH, expected_marker)
    except BaseException:
        shutil.rmtree(temporary_root, ignore_errors=True)
        raise

    backup_root = output_root.with_name(f".{output_root.name}.backup-{os.getpid()}")
    if backup_root.exists():
        shutil.rmtree(backup_root)
    if output_root.exists():
        output_root.replace(backup_root)
    try:
        temporary_root.replace(output_root)
    except BaseException:
        if backup_root.exists() and not output_root.exists():
            backup_root.replace(output_root)
        shutil.rmtree(temporary_root, ignore_errors=True)
        raise
    else:
        if backup_root.exists():
            shutil.rmtree(backup_root)


def rewrite_data_parquets(
    source_root: Path,
    output_root: Path,
    *,
    config: dict[str, Any],
    policy_type: str,
    stats_episode_indices: set[int] | None = None,
    progress_annotations: dict[int, dict[str, Any]] | None = None,
    pa: Any,
    pq: Any,
    action_representation: str = "absolute_target",
) -> dict[str, dict[str, Any]] | None:
    files = sorted((source_root / "data").glob("chunk-*/file-*.parquet"))
    if not files:
        raise FileNotFoundError(f"no LeRobot v3 data parquet files found under {source_root / 'data'}")

    accumulators = make_vector_stats_accumulators()
    seen_stats_episodes: set[int] = set()
    previous_arm_targets: dict[int, tuple[int, list[float]]] = {}
    for source_path in files:
        rel_path = source_path.relative_to(source_root)
        output_path = output_root / rel_path
        output_path.parent.mkdir(parents=True, exist_ok=True)
        table = pq.read_table(source_path)
        state_rows, action_rows = build_policy_vectors_from_table(
            table,
            config=config,
            policy_type=policy_type,
            action_representation=action_representation,
            previous_arm_targets=previous_arm_targets,
        )
        state_dim, action_dim = policy_dims(config, policy_type)
        episode_indices = np.asarray(table["episode_index"].to_numpy(), dtype=np.int64)
        if stats_episode_indices is None:
            stats_mask = np.ones(episode_indices.shape, dtype=bool)
        else:
            stats_mask = np.isin(episode_indices, list(stats_episode_indices))
        if np.any(stats_mask):
            accumulators[config["state"]["key"]].update(
                np.asarray(state_rows, dtype=np.float32)[stats_mask]
            )
            accumulators[config["action"]["key"]].update(
                np.asarray(action_rows, dtype=np.float32)[stats_mask]
            )
            seen_stats_episodes.update(int(value) for value in np.unique(episode_indices[stats_mask]))
        arrays = [
            fixed_size_float_array(pa, state_rows, state_dim),
            fixed_size_float_array(pa, action_rows, action_dim),
        ]
        names = [config["state"]["key"], config["action"]["key"]]
        if progress_annotations is not None:
            progress_rows, progress_mask_rows = progress_rows_for_table(
                table,
                progress_annotations=progress_annotations,
            )
            arrays.extend(
                [
                    fixed_size_float_array(pa, progress_rows, PROGRESS_HORIZON),
                    fixed_size_bool_array(pa, progress_mask_rows, PROGRESS_HORIZON),
                ]
            )
            names.extend([PROGRESS_KEY, PROGRESS_MASK_KEY])
        for key in PRESERVED_DATA_KEYS:
            if key not in table.schema.names:
                raise KeyError(f"{source_path} is missing required key {key!r}")
            arrays.append(table[key])
            names.append(key)
        pq.write_table(pa.Table.from_arrays(arrays, names=names), output_path, compression="snappy")
    if stats_episode_indices is not None and seen_stats_episodes != stats_episode_indices:
        missing = sorted(stats_episode_indices - seen_stats_episodes)
        extra = sorted(seen_stats_episodes - stats_episode_indices)
        raise ValueError(
            f"training statistics episode coverage mismatch: missing={missing[:10]}, extra={extra[:10]}"
        )
    return {
        key: numpy_stats_to_json(accumulator.get_statistics())
        for key, accumulator in accumulators.items()
    }


def build_policy_vectors_from_table(
    table: Any,
    *,
    config: dict[str, Any],
    policy_type: str,
    action_representation: str | None = None,
    previous_arm_targets: dict[int, tuple[int, list[float]]] | None = None,
) -> tuple[list[list[float]], list[list[float]]]:
    source = config["source_dataset"]
    state_keys = source["state_keys"]
    action_keys = source["action_keys"]
    view_layout = view_layout_for_policy(config, policy_type)
    action_representation = resolve_action_representation(
        config, policy_type, action_representation
    )
    required_keys = [
        state_keys["robot_q_current"],
        state_keys["hand_state"],
        action_keys["robot_q_desired"],
        action_keys["hand_cmd"],
    ]
    if view_layout == "real_g1_relative_eef_relative_joints":
        validate_source_eef_pose_format(source)
        required_keys.extend([state_keys["ee_state"], action_keys["ee_action"]])
    for key in required_keys:
        if key not in table.schema.names:
            raise KeyError(f"source table is missing required key {key!r}")

    robot_q_current = table[state_keys["robot_q_current"]].to_pylist()
    hand_state = table[state_keys["hand_state"]].to_pylist()
    robot_q_desired = table[action_keys["robot_q_desired"]].to_pylist()
    hand_cmd = table[action_keys["hand_cmd"]].to_pylist()
    if view_layout == "real_g1_relative_eef_relative_joints":
        ee_state = table[state_keys["ee_state"]].to_pylist()
        ee_action = table[action_keys["ee_action"]].to_pylist()
        state_rows: list[list[float]] = []
        action_rows: list[list[float]] = []
        for current_eef, target_eef, current, desired, hand, cmd in zip(
            ee_state,
            ee_action,
            robot_q_current,
            robot_q_desired,
            hand_state,
            hand_cmd,
            strict=True,
        ):
            state, action = _mapping.map_source_row_to_real_g1_relative_eef(
                ee_state=as_float_list(current_eef),
                ee_action=as_float_list(target_eef),
                robot_q_current=as_float_list(current),
                robot_q_desired=as_float_list(desired),
                hand_state=as_float_list(hand),
                hand_cmd=as_float_list(cmd),
            )
            state_rows.append(state)
            action_rows.append(action)
        return state_rows, action_rows

    episode_indices: list[int] | None = None
    frame_indices: list[int] | None = None
    if action_representation == delta_action.ACTION_REPRESENTATION:
        for key in ("episode_index", "frame_index"):
            if key not in table.schema.names:
                raise KeyError(f"source table is missing required key {key!r} for delta actions")
        episode_indices = [int(value) for value in table["episode_index"].to_pylist()]
        frame_indices = [int(value) for value in table["frame_index"].to_pylist()]
        if previous_arm_targets is None:
            previous_arm_targets = {}

    state_rows: list[list[float]] = []
    action_rows: list[list[float]] = []
    for row_index, (current, hand, desired, cmd) in enumerate(zip(
        robot_q_current,
        hand_state,
        robot_q_desired,
        hand_cmd,
        strict=True,
    )):
        row = {
            config["state"]["key"]: as_float_list(current) + as_float_list(hand),
            config["action"]["key"]: as_float_list(desired) + as_float_list(cmd),
        }
        if view_layout == "robot_q_state19_action16":
            row = _mapping.map_robot_q_row_to_upper_body(row)
        state_rows.append(row[config["state"]["key"]])
        absolute_action = row[config["action"]["key"]]
        if action_representation == delta_action.ACTION_REPRESENTATION:
            assert episode_indices is not None
            assert frame_indices is not None
            assert previous_arm_targets is not None
            episode_index = episode_indices[row_index]
            frame_index = frame_indices[row_index]
            previous = previous_arm_targets.get(episode_index)
            previous_target = (
                previous[1] if previous is not None and frame_index == previous[0] + 1 else None
            )
            action_rows.append(
                delta_action.encode_action(
                    state=state_rows[-1],
                    absolute_action=absolute_action,
                    previous_arm_target=previous_target,
                )
            )
            previous_arm_targets[episode_index] = (frame_index, absolute_action[: delta_action.ARM_DIM])
        else:
            action_rows.append(absolute_action)
    return state_rows, action_rows


def rewrite_episode_metadata(
    source_root: Path,
    output_root: Path,
    *,
    config: dict[str, Any],
    policy_type: str,
    pa: Any,
    pq: Any,
    action_representation: str = "absolute_target",
) -> None:
    files = sorted((source_root / "meta" / "episodes").glob("chunk-*/file-*.parquet"))
    if not files:
        episode_root = source_root / "meta" / "episodes"
        raise FileNotFoundError(f"no LeRobot v3 episode metadata files found under {episode_root}")
    video_map = training_video_map(config)
    for source_path in files:
        table = pq.read_table(source_path)
        arrays: list[Any] = []
        names: list[str] = []
        for key in PRESERVED_EPISODE_KEYS:
            if key in table.schema.names:
                arrays.append(table[key])
                names.append(key)
        for target_key, source_key in video_map.items():
            for suffix in VIDEO_EPISODE_SUFFIXES:
                source_col = f"videos/{source_key}/{suffix}"
                target_col = f"videos/{target_key}/{suffix}"
                if source_col not in table.schema.names:
                    raise KeyError(f"{source_path} is missing required video metadata {source_col!r}")
                arrays.append(table[source_col])
                names.append(target_col)
        add_episode_stats_columns(
            table,
            arrays,
            names,
            config=config,
            policy_type=policy_type,
            action_representation=action_representation,
        )
        for key in ("meta/episodes/chunk_index", "meta/episodes/file_index"):
            if key in table.schema.names:
                arrays.append(table[key])
                names.append(key)

        rel_path = source_path.relative_to(source_root)
        output_path = output_root / rel_path
        output_path.parent.mkdir(parents=True, exist_ok=True)
        pq.write_table(pa.Table.from_arrays(arrays, names=names), output_path, compression="snappy")


def add_episode_stats_columns(
    table: Any,
    arrays: list[Any],
    names: list[str],
    *,
    config: dict[str, Any],
    policy_type: str,
    action_representation: str = "absolute_target",
) -> None:
    source = config["source_dataset"]
    if view_layout_for_policy(config, policy_type) != "real_g1_relative_eef_relative_joints":
        state_prefixes = [
            f"stats/{source['state_keys']['robot_q_current']}",
            f"stats/{source['state_keys']['hand_state']}",
        ]
        action_prefixes = [
            f"stats/{source['action_keys']['robot_q_desired']}",
            f"stats/{source['action_keys']['hand_cmd']}",
        ]
        state_index_map, action_index_map = stats_index_maps(config, policy_type)
        for stat_name in STATS_NAMES:
            add_combined_episode_stat(
                table,
                arrays,
                names,
                target_prefix=f"stats/{config['state']['key']}",
                stat_name=stat_name,
                source_prefixes=state_prefixes,
                index_map=state_index_map,
            )
            if action_representation != delta_action.ACTION_REPRESENTATION:
                add_combined_episode_stat(
                    table,
                    arrays,
                    names,
                    target_prefix=f"stats/{config['action']['key']}",
                    stat_name=stat_name,
                    source_prefixes=action_prefixes,
                    index_map=action_index_map,
                )

    for target_key, source_key in training_video_map(config).items():
        for stat_name in STATS_NAMES:
            copy_episode_column(
                table,
                arrays,
                names,
                source_col=f"stats/{source_key}/{stat_name}",
                target_col=f"stats/{target_key}/{stat_name}",
                required=False,
            )
    for key in PRESERVED_DATA_KEYS:
        for stat_name in STATS_NAMES:
            copy_episode_column(
                table,
                arrays,
                names,
                source_col=f"stats/{key}/{stat_name}",
                target_col=f"stats/{key}/{stat_name}",
                required=False,
            )


def add_combined_episode_stat(
    table: Any,
    arrays: list[Any],
    names: list[str],
    *,
    target_prefix: str,
    stat_name: str,
    source_prefixes: list[str],
    index_map: list[int | None],
) -> None:
    columns = [f"{prefix}/{stat_name}" for prefix in source_prefixes]
    if any(column not in table.schema.names for column in columns):
        return
    if stat_name == "count":
        arrays.append(table[columns[0]])
        names.append(f"{target_prefix}/{stat_name}")
        return
    combined_rows = [
        map_stat_values(concat_lists(values), index_map)
        for values in zip(*(table[column].to_pylist() for column in columns), strict=True)
    ]
    arrays.append(combined_rows)
    names.append(f"{target_prefix}/{stat_name}")


def copy_episode_column(
    table: Any,
    arrays: list[Any],
    names: list[str],
    *,
    source_col: str,
    target_col: str,
    required: bool,
) -> None:
    if source_col not in table.schema.names:
        if required:
            raise KeyError(f"episode metadata is missing required column {source_col!r}")
        return
    arrays.append(table[source_col])
    names.append(target_col)


def link_video_dirs(source_root: Path, output_root: Path, video_map: dict[str, str]) -> None:
    for target_key, source_key in video_map.items():
        source_dir = source_root / "videos" / source_key
        if not source_dir.exists():
            raise FileNotFoundError(f"source video directory missing: {source_dir}")
        target_dir = output_root / "videos" / target_key
        target_dir.parent.mkdir(parents=True, exist_ok=True)
        relative_source = os.path.relpath(source_dir, target_dir.parent)
        target_dir.symlink_to(relative_source, target_is_directory=True)


def build_training_features(
    *,
    config: dict[str, Any],
    policy_type: str,
    source_features: dict[str, Any],
    action_representation: str = "absolute_target",
    include_progress: bool = False,
) -> dict[str, Any]:
    features: dict[str, Any] = {}
    for target_key, source_key in training_video_map(config).items():
        if source_key not in source_features:
            raise KeyError(f"source features are missing camera key {source_key!r}")
        features[target_key] = normalize_visual_feature(source_features[source_key])

    state_dim, action_dim = policy_dims(config, policy_type)
    state_names, action_names = policy_names(config, policy_type, action_representation)
    features[config["state"]["key"]] = {
        "dtype": "float32",
        "shape": [state_dim],
        "names": state_names,
    }
    features[config["action"]["key"]] = {
        "dtype": "float32",
        "shape": [action_dim],
        "names": action_names,
    }
    if include_progress:
        features[PROGRESS_KEY] = {
            "dtype": "float32",
            "shape": [PROGRESS_HORIZON],
            "names": [f"progress_t+{index}" for index in range(PROGRESS_HORIZON)],
        }
        features[PROGRESS_MASK_KEY] = {
            "dtype": "bool",
            "shape": [PROGRESS_HORIZON],
            "names": [f"progress_valid_t+{index}" for index in range(PROGRESS_HORIZON)],
        }
    for key in PRESERVED_DATA_KEYS:
        if key in source_features:
            features[key] = copy.deepcopy(source_features[key])
    return features


def normalize_visual_feature(feature: dict[str, Any]) -> dict[str, Any]:
    normalized = copy.deepcopy(feature)
    if normalized.get("dtype") not in {"image", "video"}:
        return normalized
    shape = normalized.get("shape", [])
    if not isinstance(shape, list) or len(shape) != 3:
        return normalized

    if shape[-1] in (1, 3, 4):
        normalized["names"] = ["height", "width", "channels"]
    elif shape[0] in (1, 3, 4):
        normalized["names"] = ["channels", "height", "width"]
    else:
        normalized["names"] = ["height", "width", "channels"]
    return normalized


def build_training_stats(
    *,
    config: dict[str, Any],
    policy_type: str,
    source_stats: dict[str, Any],
    source_features: dict[str, Any],
    mapped_vector_stats: dict[str, dict[str, Any]] | None = None,
    action_representation: str = "absolute_target",
) -> dict[str, Any]:
    source = config["source_dataset"]
    if mapped_vector_stats is not None:
        stats = copy.deepcopy(mapped_vector_stats)
    else:
        state_stats = concat_stat_entries(
            [
                source_stats[source["state_keys"]["robot_q_current"]],
                source_stats[source["state_keys"]["hand_state"]],
            ]
        )
        action_stats = concat_stat_entries(
            [
                source_stats[source["action_keys"]["robot_q_desired"]],
                source_stats[source["action_keys"]["hand_cmd"]],
            ]
        )
        state_index_map, action_index_map = stats_index_maps(config, policy_type)
        stats = {
            config["state"]["key"]: map_stat_entry(state_stats, state_index_map),
            config["action"]["key"]: map_stat_entry(action_stats, action_index_map),
        }
    for target_key, source_key in training_video_map(config).items():
        if source_key in source_stats:
            stats[target_key] = copy.deepcopy(source_stats[source_key])
    for key in PRESERVED_DATA_KEYS:
        if key in source_stats and key in source_features:
            stats[key] = copy.deepcopy(source_stats[key])
    return stats


def concat_stat_entries(entries: list[dict[str, Any]]) -> dict[str, Any]:
    combined: dict[str, Any] = {}
    for stat_name in STATS_NAMES:
        if any(stat_name not in entry for entry in entries):
            continue
        if stat_name == "count":
            combined[stat_name] = copy.deepcopy(entries[0][stat_name])
            continue
        combined[stat_name] = concat_lists(entry[stat_name] for entry in entries)
    return combined


def make_vector_stats_accumulators() -> dict[str, Any]:
    from lerobot.datasets.compute_stats import RunningQuantileStats

    return {
        "observation.state": RunningQuantileStats(),
        "action": RunningQuantileStats(),
    }


def numpy_stats_to_json(stats: dict[str, Any]) -> dict[str, Any]:
    return {
        key: value.tolist() if isinstance(value, np.ndarray) else copy.deepcopy(value)
        for key, value in stats.items()
    }


def map_stat_entry(entry: dict[str, Any], index_map: list[int | None]) -> dict[str, Any]:
    mapped: dict[str, Any] = {}
    for stat_name, values in entry.items():
        if stat_name == "count":
            mapped[stat_name] = copy.deepcopy(values)
            continue
        mapped[stat_name] = map_stat_values(values, index_map)
    return mapped


def stats_index_maps(config: dict[str, Any], policy_type: str) -> tuple[list[int | None], list[int | None]]:
    view_layout = view_layout_for_policy(config, policy_type)
    if view_layout == "real_g1_relative_eef_relative_joints":
        raise ValueError("relative-EEF ROT6D statistics cannot be produced with an index-only mapping")
    if view_layout == "robot_q_current_robot_q_desired_38d":
        return list(range(_mapping.SOURCE_STATE_DIM)), list(range(_mapping.SOURCE_ACTION_DIM))
    if view_layout == "robot_q_state19_action16":
        return list(_mapping.UPPER_BODY_SOURCE_INDEX_MAP), list(_mapping.UPPER_BODY_SOURCE_INDEX_MAP)
    raise ValueError(f"unsupported policy view layout {view_layout!r}")


def map_stat_values(values: list[Any], index_map: list[int | None]) -> list[Any]:
    return [0.0 if index is None else copy.deepcopy(values[index]) for index in index_map]


def training_video_map(config: dict[str, Any]) -> dict[str, str]:
    camera_map = config["source_dataset"]["camera_map"]
    result = {
        f"observation.images.{camera_name}": camera_map[camera_name]
        for camera_name in config["cameras"]
        if camera_name != "head_right"
    }
    if tuple(result) != (
        "observation.images.head_left",
        "observation.images.left_wrist",
        "observation.images.right_wrist",
    ):
        raise ValueError(
            "training cameras must be exactly head_left, left_wrist, right_wrist in that order"
        )
    if len(set(result.values())) != len(result):
        raise ValueError(f"source camera mapping contains aliases: {result}")
    return result


def ignored_source_video_keys(source_features: dict[str, Any], video_map: dict[str, str]) -> list[str]:
    selected = set(video_map.values())
    return sorted(
        key
        for key, feature in source_features.items()
        if isinstance(feature, dict)
        and feature.get("dtype") == "video"
        and key.startswith("observation.images.")
        and key not in selected
    )


def policy_dims(config: dict[str, Any], policy_type: str) -> tuple[int, int]:
    view_layout = view_layout_for_policy(config, policy_type)
    if view_layout == "real_g1_relative_eef_relative_joints":
        return _mapping.REAL_G1_RELATIVE_EEF_STATE_DIM, _mapping.REAL_G1_RELATIVE_EEF_ACTION_DIM
    if view_layout == "robot_q_state19_action16":
        return _mapping.UPPER_BODY_STATE_DIM, _mapping.UPPER_BODY_ACTION_DIM
    return _mapping.SOURCE_STATE_DIM, _mapping.SOURCE_ACTION_DIM


def policy_names(
    config: dict[str, Any], policy_type: str, action_representation: str | None = None
) -> tuple[list[str], list[str]]:
    view_layout = view_layout_for_policy(config, policy_type)
    if view_layout == "real_g1_relative_eef_relative_joints":
        return (
            list(_mapping.REAL_G1_RELATIVE_EEF_STATE_NAMES),
            list(_mapping.REAL_G1_RELATIVE_EEF_ACTION_NAMES),
        )
    if view_layout == "robot_q_state19_action16":
        action_representation = resolve_action_representation(
            config, policy_type, action_representation
        )
        action_names = list(_mapping.UPPER_BODY_ACTION_NAMES)
        if action_representation == delta_action.ACTION_REPRESENTATION:
            action_names = [
                f"{name.removesuffix('_target')}_delta" for name in action_names[: delta_action.ARM_DIM]
            ] + action_names[delta_action.ARM_DIM :]
        return list(_mapping.UPPER_BODY_STATE_NAMES), action_names
    return full_robot_q_state_names(), full_robot_q_action_names()


def control_scope_for_policy(config: dict[str, Any], policy_type: str) -> str:
    if policy_type == "groot":
        return "upper_body_relative_eef"
    value = os.environ.get("CONTROL_SCOPE", config.get("training", {}).get("control_scope", "upper_body"))
    value = str(value).strip().lower()
    if value not in {"upper_body", "full_robot_q"}:
        raise ValueError("CONTROL_SCOPE must be 'upper_body' or 'full_robot_q'")
    return value


def view_layout_for_policy(config: dict[str, Any], policy_type: str) -> str:
    if policy_type == "groot":
        return "real_g1_relative_eef_relative_joints"
    if control_scope_for_policy(config, policy_type) == "upper_body":
        return "robot_q_state19_action16"
    return "robot_q_current_robot_q_desired_38d"


def full_robot_q_state_names() -> list[str]:
    return [f"robot_q_current_{index}" for index in range(_mapping.SOURCE_ROBOT_Q_DIM)] + [
        "left_gripper_q",
        "right_gripper_q",
    ]


def full_robot_q_action_names() -> list[str]:
    return [f"robot_q_desired_{index}" for index in range(_mapping.SOURCE_ROBOT_Q_DIM)] + [
        "left_gripper_q_cmd",
        "right_gripper_q_cmd",
    ]


def fixed_size_float_array(pa: Any, rows: list[list[float]], size: int) -> Any:
    flat: list[float] = []
    for row in rows:
        if len(row) != size:
            raise ValueError(f"expected {size}-D vector, got {len(row)}")
        values = [float(value) for value in row]
        if not all(math.isfinite(value) for value in values):
            raise ValueError("policy vector contains NaN or Inf")
        flat.extend(values)
    return pa.FixedSizeListArray.from_arrays(pa.array(flat, type=pa.float32()), size)


def fixed_size_bool_array(pa: Any, rows: list[list[bool]], size: int) -> Any:
    flat: list[bool] = []
    for row in rows:
        if len(row) != size:
            raise ValueError(f"expected {size}-D boolean vector, got {len(row)}")
        flat.extend(bool(value) for value in row)
    return pa.FixedSizeListArray.from_arrays(pa.array(flat, type=pa.bool_()), size)


def load_progress_sidecar(path: Path) -> dict[int, dict[str, Any]]:
    if not path.is_file():
        raise FileNotFoundError(path)
    annotations: dict[int, dict[str, Any]] = {}
    for line_number, raw_line in enumerate(path.read_text().splitlines(), start=1):
        if not raw_line.strip():
            continue
        item = json.loads(raw_line)
        if item.get("schema_version") != "flip_table_event_progress_v1":
            raise ValueError(f"unsupported progress schema at {path}:{line_number}")
        episode_index = int(item["episode_index"])
        if episode_index in annotations:
            raise ValueError(f"duplicate progress annotation for episode {episode_index}")
        length = int(item["length"])
        if len(item["progress"]) != length or len(item["progress_mask"]) != length:
            raise ValueError(f"progress length mismatch for episode {episode_index}")
        annotations[episode_index] = item
    if not annotations:
        raise ValueError(f"progress sidecar is empty: {path}")
    return annotations


def progress_rows_for_table(
    table: Any,
    *,
    progress_annotations: dict[int, dict[str, Any]],
) -> tuple[list[list[float]], list[list[bool]]]:
    if "episode_index" not in table.schema.names or "frame_index" not in table.schema.names:
        raise KeyError("progress materialization requires episode_index and frame_index")
    cache: dict[int, tuple[list[list[float]], list[list[bool]]]] = {}
    values: list[list[float]] = []
    masks: list[list[bool]] = []
    for episode_value, frame_value in zip(
        table["episode_index"].to_pylist(),
        table["frame_index"].to_pylist(),
        strict=True,
    ):
        episode_index = int(episode_value)
        frame_index = int(frame_value)
        annotation = progress_annotations.get(episode_index)
        if annotation is None:
            raise KeyError(f"missing progress annotation for episode {episode_index}")
        if episode_index not in cache:
            cache[episode_index] = progress_horizons(
                annotation["progress"],
                annotation["progress_mask"],
                horizon=PROGRESS_HORIZON,
            )
        episode_values, episode_masks = cache[episode_index]
        if not 0 <= frame_index < len(episode_values):
            raise IndexError(
                f"frame {frame_index} is outside progress annotation for episode {episode_index}"
            )
        values.append(episode_values[frame_index])
        masks.append(episode_masks[frame_index])
    return values, masks


def as_float_list(values: list[Any]) -> list[float]:
    if not isinstance(values, (list, tuple)):
        raise TypeError(f"numeric feature row must be a list, got {type(values).__name__}")
    result = [float(value) for value in values]
    if not all(math.isfinite(value) for value in result):
        raise ValueError("source numeric feature contains NaN or Inf")
    return result


def concat_lists(values: Any) -> list[Any]:
    result: list[Any] = []
    for value in values:
        result.extend(copy.deepcopy(value))
    return result


def build_marker(
    *,
    repo_id: str,
    source_root: Path,
    config: dict[str, Any],
    policy_type: str,
    training_condition: str | None = None,
    source_revision: str | None = None,
    action_representation: str = "absolute_target",
    validation_fraction: float | None = None,
    heldout_episode_indices: list[int] | None = None,
    training_episode_indices: list[int] | None = None,
    source_fingerprint: str | None = None,
    progress_sidecar: Path | None = None,
) -> dict[str, Any]:
    video_map = training_video_map(config)
    return {
        "schema_version": "team_ramen_training_view_v6",
        "source_repo_id": repo_id,
        "source_root": source_root.as_posix(),
        "source_fingerprint_sha256": source_fingerprint or source_dataset_fingerprint(source_root),
        "policy_type": policy_type,
        "training_condition": training_condition,
        "source_revision": source_revision or infer_snapshot_revision(source_root),
        "view_layout": view_layout_for_policy(config, policy_type),
        "camera_map": video_map,
        "ignored_source_video_keys": ignored_source_video_keys(
            read_json(source_root / "meta" / "info.json")["features"],
            video_map,
        ),
        "state_sources": config["source_dataset"]["state_keys"],
        "action_sources": config["source_dataset"]["action_keys"],
        "source_eef_pose_format": config["source_dataset"].get("eef_pose_format"),
        "action_representation": action_representation,
        "action_semantics": action_semantics_for_policy(
            config, policy_type, action_representation
        ),
        "episode_split": {
            **config.get("validation", {}),
            "validation_fraction_override": validation_fraction,
            "fixed_heldout_episode_indices": heldout_episode_indices,
            "fixed_training_episode_indices": training_episode_indices,
        },
        "state_action_statistics": "training_episodes_only",
        "progress_sidecar": (
            {
                "path": progress_sidecar.resolve().as_posix(),
                "sha256": sha256_file(progress_sidecar),
                "policy_input": False,
                "auxiliary_target_only": True,
            }
            if progress_sidecar is not None
            else None
        ),
        "groot_embodiment_tag": (
            _mapping.REAL_G1_RELATIVE_EEF_EMBODIMENT_TAG if policy_type == "groot" else None
        ),
    }


def infer_snapshot_revision(source_root: Path) -> str | None:
    """Return an immutable Hub snapshot name when the local layout provides one."""
    name = source_root.name
    return name if len(name) == 40 and all(character in "0123456789abcdef" for character in name) else None


def action_semantics_for_policy(
    config: dict[str, Any], policy_type: str, action_representation: str | None = None
) -> str:
    if policy_type == "groot":
        return (
            "absolute EEF/joint targets in REAL_G1 slots; the N1.7 processor converts "
            "EEF with inv(T_current)@T_target and arm joints with target-current per action chunk"
        )
    if view_layout_for_policy(config, policy_type) == "robot_q_state19_action16":
        if resolve_action_representation(config, policy_type, action_representation) == delta_action.ACTION_REPRESENTATION:
            return delta_action.ACTION_SEMANTICS
        return "upper-body absolute joint target"
    return "full robot_q absolute joint target"


def validate_source_contract(source_root: Path, config: dict[str, Any]) -> None:
    required_files = (
        source_root / "meta" / "info.json",
        source_root / "meta" / "stats.json",
        source_root / "meta" / "tasks.parquet",
    )
    missing_files = [str(path) for path in required_files if not path.is_file()]
    if missing_files:
        raise FileNotFoundError(f"source dataset metadata is incomplete: {missing_files}")

    info = read_json(source_root / "meta" / "info.json")
    if not str(info.get("codebase_version", "")).startswith("v3"):
        raise ValueError(f"source dataset must be LeRobotDataset v3, got {info.get('codebase_version')!r}")
    expected_fps = float(config["fps"])
    if not math.isclose(float(info.get("fps", -1)), expected_fps, abs_tol=1.0e-9):
        raise ValueError(f"source dataset fps must be {expected_fps:g}, got {info.get('fps')!r}")
    if int(info.get("total_episodes", 0)) <= 0 or int(info.get("total_frames", 0)) <= 0:
        raise ValueError("source dataset must contain at least one episode and frame")

    features = info.get("features")
    if not isinstance(features, dict):
        raise ValueError("source dataset info.json has no feature mapping")
    source = config["source_dataset"]
    required_numeric = {
        source["state_keys"]["ee_state"]: 12,
        source["state_keys"]["robot_q_current"]: _mapping.SOURCE_ROBOT_Q_DIM,
        source["state_keys"]["hand_state"]: 2,
        source["action_keys"]["ee_action"]: 12,
        source["action_keys"]["robot_q_desired"]: _mapping.SOURCE_ROBOT_Q_DIM,
        source["action_keys"]["hand_cmd"]: 2,
    }
    for key, dimension in required_numeric.items():
        feature = features.get(key)
        if not isinstance(feature, dict) or feature.get("dtype") != "float32" or feature.get("shape") != [dimension]:
            raise ValueError(f"source feature {key!r} must be float32[{dimension}], got {feature!r}")

    expected_shape = [
        int(config["image"]["height"]),
        int(config["image"]["width"]),
        int(config["image"]["channels"]),
    ]
    for source_key in training_video_map(config).values():
        feature = features.get(source_key)
        video_info = feature.get("info", {}) if isinstance(feature, dict) else {}
        if (
            not isinstance(feature, dict)
            or feature.get("dtype") != "video"
            or feature.get("shape") != expected_shape
            or float(video_info.get("video.fps", -1)) != expected_fps
        ):
            raise ValueError(
                f"source camera {source_key!r} must be {expected_shape} video at {expected_fps:g} fps, "
                f"got {feature!r}"
            )
        if not (source_root / "videos" / source_key).is_dir():
            raise FileNotFoundError(f"source camera directory is missing: {source_root / 'videos' / source_key}")


def source_dataset_fingerprint(source_root: Path) -> str:
    files: list[Path] = []
    for relative in ("meta/info.json", "meta/stats.json", "meta/tasks.parquet"):
        path = source_root / relative
        if path.is_file():
            files.append(path)
    files.extend(sorted((source_root / "meta" / "episodes").glob("chunk-*/*.parquet")))
    files.extend(sorted((source_root / "meta" / "augmentation").glob("**/*")))
    files.extend(sorted((source_root / "data").glob("chunk-*/*.parquet")))
    files = [path for path in files if path.is_file()]
    if not files:
        raise FileNotFoundError(f"source dataset has no fingerprintable files: {source_root}")

    digest = hashlib.sha256()
    for path in files:
        relative = path.relative_to(source_root).as_posix().encode("utf-8")
        digest.update(len(relative).to_bytes(4, "big"))
        digest.update(relative)
        with path.open("rb") as file:
            while chunk := file.read(1024 * 1024):
                digest.update(chunk)
    return digest.hexdigest()


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        while chunk := handle.read(1024 * 1024):
            digest.update(chunk)
    return digest.hexdigest()


def build_grouped_episode_split(
    source_root: Path,
    *,
    config: dict[str, Any],
    pq: Any,
    validation_fraction: float | None = None,
    heldout_episode_indices: list[int] | None = None,
    training_episode_indices: list[int] | None = None,
) -> dict[str, Any]:
    split_config = config.get("validation", {})
    validation_fraction = float(
        split_config.get("validation_fraction", 0.1)
        if validation_fraction is None
        else validation_fraction
    )
    test_fraction = float(split_config.get("test_fraction", 0.1))
    seed = int(split_config.get("seed", 42))
    if validation_fraction < 0 or test_fraction < 0 or validation_fraction + test_fraction >= 1:
        raise ValueError("validation/test fractions must be non-negative and sum to less than one")

    groups: dict[str, list[int]] = {}
    declared_split_by_group: dict[str, str] = {}
    source_split_column = str(split_config.get("source_split_column", "")).strip()
    source_split_seen = False
    source_split_missing = False
    tasks: set[tuple[str, ...]] = set()
    all_episode_indices: list[int] = []
    episode_files = sorted((source_root / "meta" / "episodes").glob("chunk-*/*.parquet"))
    if not episode_files:
        raise FileNotFoundError(f"source dataset has no episode metadata: {source_root}")
    augmentation_path = source_root / SOURCE_AUGMENTATION_PATH
    augmentation_records = (
        load_augmentation_records(augmentation_path) if augmentation_path.is_file() else None
    )
    for path in episode_files:
        schema_names = set(pq.read_schema(path).names)
        columns = ["episode_index", "tasks"]
        if source_split_column:
            if source_split_column in schema_names:
                columns.append(source_split_column)
                source_split_seen = True
            else:
                source_split_missing = True
        if augmentation_records is None:
            if "source_episode_name" not in schema_names:
                raise ValueError("source_episode_name is required for leakage-safe splitting")
            columns.append("source_episode_name")
        table = pq.read_table(path, columns=columns)
        for row in table.to_pylist():
            episode_index = int(row["episode_index"])
            if augmentation_records is None:
                source_name = str(row.get("source_episode_name", "")).strip()
                if not source_name:
                    raise ValueError("source_episode_name is required for leakage-safe splitting")
            else:
                record = augmentation_records.get(episode_index)
                if record is None:
                    raise ValueError(
                        f"episode {episode_index} is absent from augmentation lineage metadata"
                    )
                source_name = str(record["source_trajectory_lineage"])
            groups.setdefault(source_name, []).append(int(row["episode_index"]))
            if source_split_column in row:
                declared_split = str(row[source_split_column]).strip().lower()
                if declared_split == "val":
                    declared_split = "validation"
                if declared_split not in {"train", "validation", "test"}:
                    raise ValueError(
                        f"unsupported {source_split_column} value {declared_split!r}"
                    )
                previous_split = declared_split_by_group.setdefault(source_name, declared_split)
                if previous_split != declared_split:
                    raise ValueError(
                        f"source lineage {source_name!r} crosses declared dataset splits"
                    )
            all_episode_indices.append(episode_index)
            task_value = row.get("tasks")
            tasks.add(tuple(str(value) for value in (task_value if isinstance(task_value, list) else [task_value])))
    if len(tasks) != 1:
        raise ValueError(f"one subtask dataset must contain exactly one task label, got {sorted(tasks)}")
    total_episodes = int(read_json(source_root / "meta" / "info.json")["total_episodes"])
    if sorted(all_episode_indices) != list(range(total_episodes)):
        raise ValueError(
            "episode metadata indices must be unique and contiguous from 0 to total_episodes-1"
        )

    if source_split_seen and source_split_missing:
        raise ValueError(
            f"source split column {source_split_column!r} is not present in every episode shard"
        )

    if augmentation_records is None and source_split_seen:
        if heldout_episode_indices is not None or training_episode_indices is not None:
            raise ValueError("fixed episode overrides cannot replace the dataset's declared split")
        split_groups = {
            name: sorted(
                source_name
                for source_name, split in declared_split_by_group.items()
                if split == name
            )
            for name in ("train", "validation", "test")
        }
        if any(not split_groups[name] for name in ("train", "validation", "test")):
            raise ValueError("declared dataset split must contain train, validation, and test")
        group_key = f"source_episode_name+{source_split_column}"
    elif augmentation_records is None:
        group_names = sorted(groups)
        random.Random(seed).shuffle(group_names)
        if training_episode_indices is not None:
            requested_train = set(training_episode_indices)
            requested_test = set(heldout_episode_indices or [])
            available = set(all_episode_indices)
            missing = sorted((requested_train | requested_test) - available)
            if missing:
                raise ValueError(f"fixed train/test episodes do not exist: {missing}")
            if requested_train & requested_test:
                raise ValueError("fixed train and test episodes must be disjoint")
            if not requested_train or not requested_test:
                raise ValueError("fixed train/test selection must keep both splits non-empty")

            def selected_groups(requested: set[int], name: str) -> list[str]:
                names = sorted(
                    source_name
                    for source_name, episode_indices in groups.items()
                    if requested.intersection(episode_indices)
                )
                expanded = {
                    episode_index for source_name in names for episode_index in groups[source_name]
                }
                if expanded != requested:
                    raise ValueError(
                        f"fixed {name} episodes share a source recording with non-selected episodes; "
                        f"requested={sorted(requested)}, lineage-expanded={sorted(expanded)}"
                    )
                return names

            split_groups = {
                "train": selected_groups(requested_train, "training"),
                "validation": [],
                "test": selected_groups(requested_test, "held-out"),
            }
        elif heldout_episode_indices is not None:
            requested = set(heldout_episode_indices)
            available = set(all_episode_indices)
            missing = sorted(requested - available)
            if missing:
                raise ValueError(f"fixed held-out episodes do not exist: {missing}")
            test_names = sorted(
                source_name
                for source_name, episode_indices in groups.items()
                if requested.intersection(episode_indices)
            )
            expanded = {
                episode_index for source_name in test_names for episode_index in groups[source_name]
            }
            if expanded != requested:
                raise ValueError(
                    "fixed held-out episodes share a source recording with other episodes; "
                    f"requested={sorted(requested)}, lineage-expanded={sorted(expanded)}"
                )
            remaining = [name for name in group_names if name not in set(test_names)]
            validation_count = round(len(remaining) * validation_fraction)
            if validation_fraction > 0 and validation_count == 0:
                validation_count = 1
            if validation_count >= len(remaining):
                raise ValueError("fixed held-out split leaves no training source recordings")
            split_groups = {
                "test": test_names,
                "validation": remaining[:validation_count],
                "train": remaining[validation_count:],
            }
        else:
            validation_count = round(len(group_names) * validation_fraction)
            test_count = round(len(group_names) * test_fraction)
            if validation_fraction > 0 and validation_count == 0:
                validation_count = 1
            if test_fraction > 0 and test_count == 0:
                test_count = 1
            if validation_count + test_count >= len(group_names):
                raise ValueError("episode split leaves no training source recordings")
            split_groups = {
                "test": group_names[:test_count],
                "validation": group_names[test_count : test_count + validation_count],
                "train": group_names[test_count + validation_count :],
            }
        group_key = "source_episode_name"
    else:
        if heldout_episode_indices is not None:
            raise ValueError("fixed held-out episode indices require a source dataset without augmentation lineages")
        split_by_lineage: dict[str, str] = {}
        for episode_index, record in augmentation_records.items():
            lineage = str(record["source_trajectory_lineage"])
            split = str(record["split"])
            previous = split_by_lineage.setdefault(lineage, split)
            if previous != split:
                raise ValueError(f"lineage {lineage!r} crosses dataset splits")
        split_groups = {
            name: sorted(lineage for lineage, split in split_by_lineage.items() if split == name)
            for name in ("train", "validation", "test")
        }
        if not split_groups["train"] or (validation_fraction > 0 and not split_groups["validation"]):
            raise ValueError("augmentation sidecar must contain required train and validation lineages")
        group_key = "source_trajectory_lineage"
    episode_counts = {
        name: sum(len(groups[source_name]) for source_name in names)
        for name, names in split_groups.items()
    }
    payload = {
        "schema_version": "team_ramen_grouped_episode_split_v1",
        "seed": seed,
        "group_key": group_key,
        "fractions": {
            # Fixed held-out episodes are a benchmark contract, not a request
            # for the configured default test fraction.  Record the actual
            # episode-level proportions so the manifest is an honest account
            # of the examples used for each purpose.
            name: episode_counts[name] / total_episodes
            for name in ("train", "validation", "test")
        },
        "splits": {
            name: {
                "source_episode_names": names,
                "episode_indices": sorted(
                    episode_index for source_name in names for episode_index in groups[source_name]
                ),
            }
            for name, names in split_groups.items()
        },
    }
    serialized = json.dumps(payload, sort_keys=True, separators=(",", ":")).encode("utf-8")
    payload["sha256"] = hashlib.sha256(serialized).hexdigest()
    return payload


def validate_source_eef_pose_format(source_config: dict[str, Any]) -> None:
    expected = {
        "ordering": "left_then_right",
        "per_hand": "xyz_euler_xyz",
        "angle_unit": "radian",
        "reference_frame": "root_link",
    }
    actual = source_config.get("eef_pose_format")
    if actual != expected:
        raise ValueError(
            "GR00T REAL_G1 mapping requires source EEF poses in left/right "
            f"root-frame XYZ + Euler-XYZ radians; got {actual!r}"
        )


def require_pyarrow() -> tuple[Any, Any]:
    try:
        import pyarrow as pa
        import pyarrow.parquet as pq
    except ModuleNotFoundError as exc:
        raise RuntimeError("pyarrow is required to materialize the LeRobot training view") from exc
    return pa, pq


def copy_required_file(source: Path, target: Path) -> None:
    if not source.exists():
        raise FileNotFoundError(source)
    target.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(source, target)


def copy_optional_file(source: Path, target: Path) -> None:
    if source.exists():
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, target)


def read_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, data: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(json.dumps(data, ensure_ascii=False, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    tmp.replace(path)


if __name__ == "__main__":
    main()
